//! Signed checkpoints anchoring the `ssdf.audit` hash chain beyond its TTL.
//!
//! `ssdf.audit` (the ClickHouse table `verify_audit.py` walks) carries a
//! 90-day TTL. `verify_audit.py`'s chain verification starts from genesis
//! (`prev_hash == ""`) — once the earliest rows for a `(tier, server_id)`
//! chain expire, genesis is gone and the chain would appear broken even
//! though nothing was tampered with.
//!
//! A checkpoint is a durable, signed statement of a chain's head at a point
//! in time: `(tier, server_id, row_count, head_row_hash, checkpoint_ts)`.
//! Checkpoints are written to a table with no TTL
//! (`ssdf.audit_checkpoints`), so once one exists for a chain,
//! `verify_audit.py` can verify from the nearest prior checkpoint instead of
//! requiring genesis to still be present.
//!
//! ## Why sign it
//!
//! A checkpoint is itself a security-relevant claim ("this chain had exactly
//! this head, at this row count, at this time"). Storing it unsigned would
//! let anyone able to write to ClickHouse rewrite history and then plant a
//! matching checkpoint — the checkpoint would authenticate a false history as
//! confidently as it authenticates a true one. Signing means only the holder
//! of the checkpoint signing key can mint an anchor, and rotating that key is
//! the one operational control that can invalidate a bad batch.
//!
//! ## Signed bytes and encoding
//!
//! The checkpoint's fields are canonicalised (sorted keys, no incidental
//! whitespace, via [`crate::canonical`]) and hashed to a `sha256:<hex>`
//! digest ([`checkpoint_digest`]). That digest — not the JSON bytes — is what
//! gets signed, using the same primitive as segment-head signing
//! ([`crate::signing::sign_digest`]). Signatures are base64-encoded, same as
//! [`crate::signing`].
//!
//! ## Key management (v1)
//!
//! v1 is a local Ed25519 key file, generated by `mecmcp-audit-keygen` and
//! loaded with the same fail-closed 0600 permission check as evidence
//! signing keys ([`crate::signing::load_signing_key`]). The verifying key is
//! distributed alongside the checkpoint job's deployment config; operators
//! identify which key signed a given checkpoint via [`key_id`], a short
//! fingerprint of the verifying key, so a key rotation can be told apart
//! from a compromised or lost key without decoding every checkpoint's
//! signature. There is no automatic rotation: an operator rotates by
//! generating a new keypair, distributing the new verifying key alongside
//! the old one until every stored checkpoint under the old key has aged past
//! the evidence tier's retention, then retiring the old key.

use crate::canonical::{self, CanonicalError};
use crate::signing::{self, DetachedSignature, SigningError, SigningKey, VerifyingKey};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use thiserror::Error;

/// A signed anchor for one `(tier, server_id)` chain in `ssdf.audit`.
///
/// `head_row_hash` is the chain's row_hash as ClickHouse stores it: a bare
/// hex digest with **no** `sha256:` prefix (`ssdf_mcp_query.audit_chain`'s
/// format), not this crate's `sha256:<hex>` convention. It is carried
/// verbatim as an opaque string field; [`checkpoint_digest`] hashes the
/// checkpoint's own canonical JSON, so the two hash formats never collide or
/// need reconciling.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Checkpoint {
    /// The `ssdf.audit` tier this checkpoint anchors (e.g. `"evidence"`, `"sovereign"`).
    pub tier: String,
    /// The writer this checkpoint anchors within the tier. Empty for chains
    /// grouped by tier alone (rows with no `server_id`, e.g. `sovereign`).
    pub server_id: String,
    /// Number of rows in the chain at the time of this checkpoint (inclusive of genesis).
    pub row_count: u64,
    /// The chain head's `row_hash` at checkpoint time, verbatim from ClickHouse.
    pub head_row_hash: String,
    /// UTC RFC3339 timestamp of when this checkpoint was taken.
    pub checkpoint_ts: String,
}

/// Errors that can occur while signing or verifying a checkpoint.
#[derive(Debug, Error)]
pub enum CheckpointError {
    /// The checkpoint could not be canonicalised for hashing.
    #[error("checkpoint canonicalisation failed: {0}")]
    Canonical(#[from] CanonicalError),
    /// Signing or verification failed.
    #[error(transparent)]
    Signing(#[from] SigningError),
    /// The checkpoint could not be converted to a JSON value.
    #[error("checkpoint serialization failed: {0}")]
    Serde(#[from] serde_json::Error),
}

/// Compute the `sha256:<hex>` digest of a checkpoint's canonical form.
///
/// This is what gets signed, not the checkpoint's raw JSON bytes.
pub fn checkpoint_digest(checkpoint: &Checkpoint) -> Result<String, CheckpointError> {
    let value = serde_json::to_value(checkpoint)?;
    Ok(canonical::digest_of(&value)?)
}

/// Sign a checkpoint, producing a detached signature over its canonical digest.
pub fn sign_checkpoint(
    checkpoint: &Checkpoint,
    key: &SigningKey,
) -> Result<DetachedSignature, CheckpointError> {
    let digest = checkpoint_digest(checkpoint)?;
    Ok(signing::sign_digest(&digest, key)?)
}

/// Verify a signature over a checkpoint's canonical digest.
pub fn verify_checkpoint(
    checkpoint: &Checkpoint,
    signature: &DetachedSignature,
    key: &VerifyingKey,
) -> Result<(), CheckpointError> {
    let digest = checkpoint_digest(checkpoint)?;
    Ok(signing::verify_digest(&digest, signature, key)?)
}

/// A short, stable fingerprint identifying a verifying key.
///
/// Not a secret and not itself used for verification — it lets an operator
/// or an automated check tell which key signed a stored checkpoint (to
/// detect an unexpected key after rotation, or to select the right
/// verifying key when more than one is trusted during a rotation window)
/// without decoding the signature. Sixteen hex characters (64 bits) is far
/// more than needed to distinguish the handful of keys any one deployment
/// will ever hold, while staying short enough to log and grep.
pub fn key_id(key: &VerifyingKey) -> String {
    let encoded = signing::encode_verifying_key(key);
    let mut hasher = Sha256::new();
    hasher.update(encoded.as_bytes());
    let digest = hasher.finalize();
    hex::encode(&digest[..8])
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;
    use crate::signing::generate_keypair;

    fn fixture() -> Checkpoint {
        Checkpoint {
            tier: "evidence".to_string(),
            server_id: "rustsdcmcp-606".to_string(),
            row_count: 42,
            head_row_hash: "abcdef0123456789".repeat(4),
            checkpoint_ts: "2026-09-28T00:00:00.000Z".to_string(),
        }
    }

    #[test]
    fn sign_verify_roundtrip() {
        let (signing_key, verifying_key) = generate_keypair();
        let checkpoint = fixture();

        let signature = sign_checkpoint(&checkpoint, &signing_key).unwrap();
        verify_checkpoint(&checkpoint, &signature, &verifying_key).unwrap();
    }

    #[test]
    fn wrong_key_fails_verification() {
        let (signing_key, _) = generate_keypair();
        let (_, wrong_key) = generate_keypair();
        let checkpoint = fixture();

        let signature = sign_checkpoint(&checkpoint, &signing_key).unwrap();
        let result = verify_checkpoint(&checkpoint, &signature, &wrong_key);
        assert!(matches!(
            result,
            Err(CheckpointError::Signing(SigningError::VerificationFailed))
        ));
    }

    #[test]
    fn tampered_row_count_fails_verification() {
        let (signing_key, verifying_key) = generate_keypair();
        let checkpoint = fixture();
        let signature = sign_checkpoint(&checkpoint, &signing_key).unwrap();

        let mut tampered = checkpoint;
        tampered.row_count += 1;

        let result = verify_checkpoint(&tampered, &signature, &verifying_key);
        assert!(result.is_err());
    }

    #[test]
    fn tampered_head_hash_fails_verification() {
        let (signing_key, verifying_key) = generate_keypair();
        let checkpoint = fixture();
        let signature = sign_checkpoint(&checkpoint, &signing_key).unwrap();

        let mut tampered = checkpoint;
        tampered.head_row_hash = "0".repeat(64);

        let result = verify_checkpoint(&tampered, &signature, &verifying_key);
        assert!(result.is_err());
    }

    #[test]
    fn different_checkpoints_have_different_digests() {
        let a = fixture();
        let mut b = fixture();
        b.row_count += 1;

        assert_ne!(
            checkpoint_digest(&a).unwrap(),
            checkpoint_digest(&b).unwrap()
        );
    }

    #[test]
    fn digest_is_stable_across_recomputation() {
        let checkpoint = fixture();
        assert_eq!(
            checkpoint_digest(&checkpoint).unwrap(),
            checkpoint_digest(&checkpoint).unwrap()
        );
    }

    #[test]
    fn key_id_is_stable_and_distinguishes_keys() {
        let (_, key_a) = generate_keypair();
        let (_, key_b) = generate_keypair();

        assert_eq!(key_id(&key_a), key_id(&key_a));
        assert_ne!(key_id(&key_a), key_id(&key_b));
        assert_eq!(key_id(&key_a).len(), 16);
    }

    #[test]
    fn key_id_never_reveals_private_material() {
        let (signing_key, verifying_key) = generate_keypair();
        let private_encoded = signing::encode_signing_key(&signing_key);
        assert!(!key_id(&verifying_key).contains(&private_encoded));
    }
}
