[package]
name       = "mecmcp-runtime"
version.workspace    = true
edition.workspace    = true
rust-version.workspace = true
license.workspace    = true
repository.workspace = true
authors.workspace    = true

[dependencies]
anyhow      = "1"
clap        = { version = "4", features = ["derive"] }
mecmcp-auth = { version = "0.2.0", path = "../mecmcp-auth" }
rustix      = { workspace = true, features = ["process", "fs"] }
thiserror   = { workspace = true }
tokio       = { version = "1", features = ["rt", "signal", "sync"] }
tracing     = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio    = { version = "1", features = ["macros", "rt", "time"] }

[lints]
workspace = true
